### PR TITLE
update documentation to latest version with bypass diode configurabil…

### PR DESCRIPTION
**Pull request by chetan201**
update documentation to latest version with bypass diode configurability

### CODE REVIEW

**Comment by chetan201** [comment]
@amir-asgharzadeh 
Could you approve this PR for updated documentation? Thanks!

**Comment by chetan201** [comment]
Thanks @amir-asgharzadeh

**Comment by mikofski** [comment]
Hi @chetan201  and @amir-asgharzadeh thanks for updating the docs and the bypass configuration addition is fantastic, great work. There were a couple of outstanding issues

* the docs contrib page isn't rendering, not sure why, see #94
* there are some code style issues in #72 see my comments, hopefully you can address them, let me know if you have questions about using pytest or nose, and sorry if I misled you with my earlier comments about testing and exceptions, or if my comments were worded poorly - I am really impressed with the additions to bypass diode configuration, thanks!

**Comment by xjianwei520** [comment]
thank you sir, good API for users .
@chetan201 
@mikofski 
According to this  new Function, Can I built this electrical topology scenario : 
Each substring in module have two bypass diode which are Series relationship, just like picture below:
pic

**Comment by chetan201** [comment]
@xjianwei520 
That is essentially one bypass diode with double the forward voltage. You can change the Bypass diode voltage drop value from default 0.5V to your desired value. Note that since the diode is assumed to be ideal. 

Although,  I see that from your drawing, there are substrings in parallel too. That scenario won't be possible to model.

**Pull request merged**
