### PR TITLE
Better memory

### PR DESCRIPTION
**Pull request by bmeyers**
This addresses issue #35. A default instance of PVmodule now takes 56kB of RAM instead of 235kB.

### CODE REVIEW

**Comment by bmeyers** [comment]
I would like to implement a similar approach at the string and system level as well.

**Comment by mikofski** [comment]
should we close this in favor of your new PR?

also please start your new PR, so that the build server will run and everyone can see your changes, thx :)

**Comment by bmeyers** [comment]
Yes, let's close. Sorry, I'm confused on the PR front. Are you asking me to do a pull request from bm-gh34-35 to upstream/master instead of to mikofski/gh34-35?

**Comment by mikofski** [comment]
reference the new PR here, with a message like
> closed in favor of PR #<pr>
and put the new pr in the <>, github will create the link automatically and put a link in the new PR too, then when peeps are looking through the history, trying to figure out where it all went wrong, they can say:
> oh sh*t we should have kept that other PR, why did they switch fools!

**Comment by bmeyers** [comment]
closed in favor of PR #43

**Pull request closed without merging**
