### PR TITLE
update docs for v3.0

### PR DESCRIPTION
**Pull request by mikofski**
* add description of object references
* fix mistakes in document quickstart example
* add version to docs
* add release robot
* try reuse redundant code
* does `pvstr.setSuns(Ee=[X])` need to be optimized?
* try to see if there is a fix for changing cell attributes without manually copies

### CODE REVIEW

**Comment by mikofski** [comment]
fix example maybe like this:
```python
# don't need to copy cells, only need to update one reference to each of the 2 cell objects
pvsys.pvmods[0][0].pvcells[11].Tcell = 100. + 273.15  # [K] hot cells in RBD
pvsys.pvmods[0][0].pvcells[0].Tcell = 50. + 273.15  # [K] normal cells
(pvmod.Imod, pvmod.Vmod, pvmod.Pmod, pvmod.Isubstr, pvmod.Vsubstr) = pvmod.calcMod()  # update modules
(pvstr.Istring, pvstr.Vstring, pvstr.Pstring) = pvstr.calcString()  # update each string in the system
pvsys.Isys, pvsys.Vsys, pvsys.Psys = pvsys.calcSystem()
(pvsys.Imp, pvsys.Vmp, pvsys.Pmp, pvsys.Isc, pvsys.Voc, pvsys.FF, pvsys.eff) = pvsys.calcMPP_IscVocFFeff()
```

**Comment by bmeyers** [comment]
@mikofski for this part:

> does pvstr.setSuns(Ee=[X]) need to be optimized?

Can't we just treat this the same way as the `pvstr.setSuns(Ee=X)` case? See PR #46.

**Comment by bmeyers** [comment]
@mikofski I have an idea for this:

> try to see if there is a fix for changing cell attributes without manually copies

Coming soon to #46

**Comment by bmeyers** [comment]
I believe that I have `.setTemps()` methods working across the board. Same exact API as `.setSuns()`.

**Comment by bmeyers** [comment]
Just made changes to quickstart tutorial to fix the bad values and show the use of `.setTemps()` in #46

**Pull request merged**
